apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day2-network
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: day2-operations
  source:
    repoURL: https://github.com/jeanlopezxyz/cluster-gitops.git
    path: charts/network-nmstate
    targetRevision: charts
    helm:
      values: |
        global:
          enabled: true
          syncwave: "1"
        helper-operator:
          global:
            syncwave: "1"
          operators:
            nmstate:
              enabled: true
              syncwave: "1"
              namespace:
                create: true
                name: "openshift-nmstate"
              operatorgroup:
                create: true
              subscription:
                operatorName: "kubernetes-nmstate-operator"
                channel: "stable"
                source: "redhat-operators"
                sourceNamespace: "openshift-marketplace"
                approval: "Automatic"
        nmstate:
          enabled: true
          name: "nmstate"
        networkPolicies:
          bridges: []
          bonds: []
          vlans: []
        customPolicies: []
        networkAttachments:
          vlansNADs:
            enabled: true
            vlanList:
              - 270
              - 271
              - 272
              - 275
              - 276
              - 326
              - 329
              - 339
              - 340
              - 362
              - 366
              - 367
              - 368
              - 370
              - 371
              - 372
              - 376
            bridge: "br0"
            namespace: "default"
            mtu: 9000
            cniType: "cnv-bridge"
            macSpoofCheck: true
          custom: []
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-nmstate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true