apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day2-oauth
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: day2-operations
  source:
    repoURL: https://github.com/jeanlopezxyz/cluster-gitops.git
    path: charts/cluster-oauth
    targetRevision: charts
    helm:
      values: |
        oauth:
          enabled: true
        htpasswd:
          enabled: true
          secretName: "htpasswd-secret"
          users:
            - username: "admin"
              password: "redhat123"
            - username: "developer"
              password: "redhat123"
        rbac:
          clusterAdmins:
            enabled: true
            groupName: "cluster-admins"
            users:
              - "admin"
          disableSelfProvisioning:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # Manual for security
    syncOptions:
      - CreateNamespace=true