apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: day2-operations
  source:
    repoURL: https://github.com/jeanlopezxyz/cluster-gitops.git
    path: charts/network-nmstate
    targetRevision: charts
    helm:
      values: |
        global:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-nmstate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true