apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuning
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: day2-operations
  source:
    repoURL: https://github.com/jeanlopezxyz/cluster-gitops.git
    path: charts/node-tuning
    targetRevision: charts
    helm:
      values: |
        global:
          enabled: true
        machineConfig:
          master:
            enabled: true
          worker:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-cluster-node-tuning-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true